title: Easy Mina
lang: en
description: Made for zk beginners 

plugins:
    - jekyll-default-layout
    - jekyll-readme-index
    - jekyll-github-metadata
    - jekyll-titles-from-headings
    - jemoji
    - jekyll-avatar
    - jekyll-mentions
    
readme_index:
    with_frontmatter: true

destination: ./docs